name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Staging EC2
      run: |
        # Add your deployment commands here
        # For example, SSH into your EC2 and pull the latest code
        ssh ec2-user@ 13.232.159.232 "cd /path/to/your/app && git pull origin staging && npm install && npm run build"

