jobs:
  deploy_staging:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Deploy to Staging EC2
      run: |
        ssh <ubuntu>@<13.232.159.232> "cd /path/to/app && git pull origin staging && npm install && npm run build && pm2 restart <your-app-name>"
      env:
        STAGING_SSH_PRIVATE_KEY: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
